package com.teslasoft.jarvis.vip;

import android.os.Bundle;
import android.app.Activity;
import com.android.billingclient.api.BillingClient;
import com.android.billingclient.api.BillingClient.Builder;
import com.android.billingclient.api.BillingClient.*;
import com.android.billingclient.api.BillingClientStateListener;
import com.android.billingclient.api.BillingResult;
import com.android.billingclient.api.BillingResults;
import com.android.billingclient.api.BillingResult.*;
import com.android.billingclient.api.PurchasesUpdatedListener;
import android.content.Intent;
import com.teslasoft.libraries.support.R;
import android.view.View;
import android.widget.ScrollView;
import android.content.pm.PackageManager;

public class VipActivity extends Activity
{
	@Override
	public void onPointerCaptureChanged(boolean hasCapture)
	{
		// Autogenerated method
	}
	
	ScrollView scrollview;

	@Override
	public void onCreate(Bundle savedInstanceState)
	{
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_promote);
		scrollview = (ScrollView) findViewById(R.id.scrollview);
		scrollview.setVerticalScrollBarEnabled(false);
	}
	
	public void PurchaseVip(View v)
	{
		Intent transaction = new Intent(this, com.teslasoft.jarvis.vip.VipPurchaseActivity.class);
		startActivity(transaction);
	}
}
