package com.teslasoft.jarvis.vip;

import android.os.Bundle;
import android.app.Activity;
import com.android.billingclient.api.BillingClient;
import com.android.billingclient.api.BillingClient.Builder;
import com.android.billingclient.api.BillingClient.*;
import com.android.billingclient.api.BillingClientStateListener;
import com.android.billingclient.api.BillingResult;
import com.android.billingclient.api.BillingResults;
import com.android.billingclient.api.BillingResult.*;
import com.android.billingclient.api.PurchasesUpdatedListener;
import android.content.Intent;
import com.teslasoft.libraries.support.R;
import android.view.View;
import android.content.pm.PackageManager;

public class VipPurchaseActivity extends Activity
{
	@Override
	public void onPointerCaptureChanged(boolean hasCapture)
	{
		// Autogenerated method
	}

	private BillingClient mBillingClient;
	
	@Override
	public void onCreate(Bundle savedInstanceState)
	{
		super.onCreate(savedInstanceState);
		setContentView(R.layout.purchase_dialog);
	}

	@Override
	protected void onPause()
	{
		// TODO: Implement this method
		super.onPause();
	}
	
	public void Close(View v)
	{
		finishAndRemoveTask();
	}
	
	public void nulclick (View v)
	{
		
	}

	@Override
	public void onBackPressed()
	{
		// TODO: Implement this method
		super.onBackPressed();
		finishAndRemoveTask();
	}
}
