// Example of connecting Jarvis Ad Library to your app
package com.teslasoft.jarvis.ads; // Put here your package name, ex: package com.my.app

/* Connect libraries */
import android.os.*;
import android.app.*;
import android.content.*;
import android.view.*;
import android.widget.*;
import java.util.*;
import android.content.*;
import android.util.*;
import android.net.*;
import android.support.v7.appcompat.*;
import android.graphics.*;
import android.webkit.*;
import android.annotation.*;
import android.support.v7.app.*;
import java.util.*;

/* Recomendet type of class is "Activity" */
public class ShowAd extends Activity
{
	/* Declare variable adId (Identifier of ad) */
	String adId;
	
	/* This if specified method, generated by android.jar complier (Android 9 Pixelexperience) */
	/* Autogenerated method. Do not modify. If you use Android Studio you can delete these method */
	@Override
	public void onPointerCaptureChanged(boolean hasCapture)
	{
		
	}

	@Override
	public void onCreate(Bundle savedInstanceState, PersistableBundle persistentState)
	{
		super.onCreate(savedInstanceState, persistentState);
		
		/* Your code */
		// ...
		/* Set identifier of ad */
		adId = "Put here your identifier of INTERSTITIAL ad, ex: mo-pub-XXXXXXXXXXXXXXX/int";
		
		showInterstitialAd(adId);
		// ...
		/* Continue your code */
	}
	
	/* Show ad method */
	String showInterstitialAd(String mopubId)
	{
		
		/* Show interstitial ad */
		try {
			Intent intent = new Intent(Intent.ACTION_MAIN);
			intent.setComponent(new ComponentName("com.teslasoft.libraries.support","com.teslasoft.jarvis.ads.InterstitialAdActivity"));
			Bundle extr = new Bundle();
			extr.putString("adId", mopubId);
			intent.putExtras(extr);
			startActivity(intent);
		}

		catch (Exception _e)
		{
			/* Catch exception (debug)*/
			/* NullPointerException: Attempt to invoke virtual method "intent.putExtras(String)" on a null object referance... */
		}
		
		/* Beacose this function have type "String" it must return some value */
		return "";
	}
}
